global:
  scrape_interval: 15s #Scrape interval to every 15 seconds.
  evaluation_interval: 15s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor_container:8080"]
    metric_relabel_configs:
      - source_labels: ['__name__', 'instance', 'job', 'id', 'image', 'name']
        regex: '.*'
        action: keep

