# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messaggi_pb2 as messaggi__pb2


class ClientManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/mypackage.ClientManagement/SendData',
                request_serializer=messaggi__pb2.RequestData.SerializeToString,
                response_deserializer=messaggi__pb2.ResponseData.FromString,
                )
        self.SendNewSubscriber = channel.unary_unary(
                '/mypackage.ClientManagement/SendNewSubscriber',
                request_serializer=messaggi__pb2.Subscriber.SerializeToString,
                response_deserializer=messaggi__pb2.ResponseData.FromString,
                )


class ClientManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNewSubscriber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=messaggi__pb2.RequestData.FromString,
                    response_serializer=messaggi__pb2.ResponseData.SerializeToString,
            ),
            'SendNewSubscriber': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNewSubscriber,
                    request_deserializer=messaggi__pb2.Subscriber.FromString,
                    response_serializer=messaggi__pb2.ResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.ClientManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.ClientManagement/SendData',
            messaggi__pb2.RequestData.SerializeToString,
            messaggi__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNewSubscriber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.ClientManagement/SendNewSubscriber',
            messaggi__pb2.Subscriber.SerializeToString,
            messaggi__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
