# Deployment per il servizio Notifier
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier-container
        image: notifier
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "0.5" # Assegna una quantità moderata di CPU
            memory: "512Mi" # Assegna una quantità moderata di memoria
        env:
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: criptovalute
        - name: GRPC_SERVER
          value: management:50051
        - name: MITTENTE
          value: prova
        - name: PASSWORD
          value: prova
        - name: PYTHONUNBUFFERED
          value: "1"


---
# Service per il servizio Notifier. Nota: i 3 trattini sono delimitatori di documenti .yml; indicano l'inizio di un nuovo documento YAML all'interno dello stesso file.
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  type: ClusterIP
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000


---
# Deployment per il servizio Management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
      - name: management-container
        image: management
        ports:
        - containerPort: 10001
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MYSQL_HOST
          value: mysql
        - name: SERVER_GRPC
          value: notifier:50051


---
# Service per il servizio Management
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  type: ClusterIP
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001


---
# Deployment per il servizio Retrieval
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval
  template:
    metadata:
      labels:
        app: retrieval
    spec:
      containers:
      - name: retrieval-container
        image: retrieval
        ports:
        - containerPort: 20002
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: INTERVAL_TIME_SECONDS
          value: "120"
        - name: PYTHONUNBUFFERED
          value: "1"


---
# Service per il servizio Retrieval
apiVersion: v1
kind: Service
metadata:
  name: retrieval-service
spec:
  type: ClusterIP
  selector:
    app: retrieval
  ports:
    - protocol: TCP
      port: 20002
      targetPort: 20002


---
# Deployment per il servizio MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        resources:
          limits:
            cpu: "0.5"  #Assegna 0.5 unità di CPU
            memory: "512Mi"   #Assegna 512 megabyte di memoria
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password


---
# Service per il servizio MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin/phpmyadmin
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: PMA_HOST
          value: "mysql-service"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: "root"
        - name: PMA_PASSWORD
          value: "password"
        - name: PMA_ARBITRARY
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-container
        image: confluentinc/cp-zookeeper:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP

